table 'visCpbtesItems Depo'
	lineageTag: 37990b63-9af7-4b99-863d-91245d0cf588

	measure 'Importe Venta Depo' = CALCULATE(SUM('visCpbtesItems Depo'[Importe]),'visCpbtesItems Depo'[Id_TipoComprobante]="PREVEN")
		lineageTag: 7af7c3cc-97c3-4d79-8306-6115a61c89a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cantidad Venta Depo' = CALCULATE(SUM('visCpbtesItems Depo'[Cantidad2]),'visCpbtesItems Depo'[Id_TipoComprobante]="PREVEN")
		formatString: 0
		lineageTag: e149800c-a69b-4502-836d-c04d5d550eac

	column Id_Comprobante
		dataType: int64
		formatString: 0
		lineageTag: f4d2ea8d-3099-4e06-bc44-44bf537c605d
		summarizeBy: none
		sourceColumn: Id_Comprobante

		annotation SummarizationSetBy = Automatic

	column Id_Producto
		dataType: int64
		formatString: 0
		lineageTag: 3ec56013-c2cb-4573-8d4d-8137d67f6c50
		summarizeBy: none
		sourceColumn: Id_Producto

		annotation SummarizationSetBy = Automatic

	column Id_Concepto
		dataType: int64
		formatString: 0
		lineageTag: 0ffb852f-f8e1-44c4-9f0f-7adf68abc482
		summarizeBy: sum
		sourceColumn: Id_Concepto

		annotation SummarizationSetBy = Automatic

	column Descripcion
		dataType: string
		lineageTag: 835d6b25-e545-4a41-8623-7e7d1fe07a8c
		summarizeBy: none
		sourceColumn: Descripcion

		annotation SummarizationSetBy = Automatic

	column Cantidad
		dataType: double
		lineageTag: c72f5377-b658-430a-800b-330145bb4653
		summarizeBy: sum
		sourceColumn: Cantidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cantidad2
		dataType: int64
		formatString: 0
		lineageTag: 5b239861-d397-4ba5-9d94-2f0b0ee45517
		summarizeBy: sum
		sourceColumn: Cantidad2

		annotation SummarizationSetBy = Automatic

	column Importe_Neto
		dataType: double
		lineageTag: fa5206e4-88cb-4e9f-9e0e-e53beea241c3
		summarizeBy: sum
		sourceColumn: Importe_Neto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IVA
		dataType: double
		lineageTag: 5de1412e-20a6-4ee6-bcda-089cb9ffd5c2
		summarizeBy: sum
		sourceColumn: IVA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Importe
		dataType: double
		lineageTag: 041bc7a7-4fca-4356-999a-d654fe3163ff
		summarizeBy: sum
		sourceColumn: Importe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Importe_Desc_Extra
		dataType: double
		lineageTag: c023be14-b843-4901-b4f9-2e84a21eeaa0
		summarizeBy: sum
		sourceColumn: Importe_Desc_Extra

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Precio_Costo
		dataType: double
		lineageTag: c3d61656-4f7f-4f0c-a2c6-24c52f9ac272
		summarizeBy: sum
		sourceColumn: Precio_Costo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Precio_IVA
		dataType: double
		lineageTag: 66630b25-483a-41ce-a71a-e8e5124cc967
		summarizeBy: sum
		sourceColumn: Precio_IVA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Importe_Descuento
		dataType: double
		lineageTag: 23aec9fe-2882-4c65-a703-72e1dc67e2b1
		summarizeBy: sum
		sourceColumn: Importe_Descuento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fecha_Comprobante
		dataType: dateTime
		formatString: General Date
		lineageTag: cdcaaa75-01b3-4476-8321-fbb82fc4a1da
		summarizeBy: none
		sourceColumn: Fecha_Comprobante

		variation Variación
			isDefault
			relationship: 09ce94cc-cde0-4d01-987e-db936fce54d0
			defaultHierarchy: LocalDateTable_4bb5f650-a38d-4c2a-961c-d17493b76a31.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Id_TipoComprobante
		dataType: string
		lineageTag: 36679fd8-0986-43ff-9bdc-fdde6f192f68
		summarizeBy: none
		sourceColumn: Id_TipoComprobante

		annotation SummarizationSetBy = Automatic

	column Id_Contacto
		dataType: string
		lineageTag: 43941df9-a35e-4231-b33e-8870ea293c89
		summarizeBy: none
		sourceColumn: Id_Contacto

		annotation SummarizationSetBy = Automatic

	partition 'visCpbtesItems Depo' = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("200.89.174.198,25015"),
				    DISTRIB_DEPO = Origen{[Name="DISTRIB_DEPO"]}[Data],
				    dbo_visComprobantesItems = DISTRIB_DEPO{[Schema="dbo",Item="visComprobantesItems"]}[Data]
				in
				    dbo_visComprobantesItems

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

